import type Stream from 'stream';

declare module 'stream-to-promise' {
  declare module.exports: (Stream) => Promise<mixed>;

  /**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

  // Filename aliases
  // flow-typed signature: 12cc06ec4eabfdece56c72e39991173d
  // flow-typed version: <<STUB>>/stream-to-promise_v2.2.0/flow_v0.40.0

  /**
 * This is an autogenerated libdef stub for:
 *
 *   'stream-to-promise'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */
}
declare module 'stream-to-promise/index' {
  declare module.exports: $Exports<'stream-to-promise'>;
}
declare module 'stream-to-promise/index.js' {
  declare module.exports: $Exports<'stream-to-promise'>;
}
